import test from 'node:test';import assert from 'node:assert/strict';import PizZip from 'pizzip';
import {certificateBytes,nameCardBytes,inspectTemplate,renderTemplate,mergeTemplateDocuments,zipFiles} from '../lib/documents.mjs';
const xml=b=>new PizZip(b).file('word/document.xml').asText();
test('uploaded DOCX fields render Chinese and XML-sensitive text without losing template borders',async()=>{const bytes=await certificateBytes([{'姓名':'{姓名}','奖项':'{奖项}'}]);assert.deepEqual(inspectTemplate(bytes).fields,['姓名','奖项']);const a=renderTemplate(bytes,{'姓名':'陈 & 林','奖项':'一等奖'});const b=renderTemplate(bytes,{'姓名':'李四','奖项':'二等奖'});const merged=xml(mergeTemplateDocuments([a,b]));assert.match(merged,/陈 &amp; 林/);assert.match(merged,/李四/);assert.match(merged,/一等奖/);assert.match(merged,/二等奖/);assert.equal((merged.match(/<w:sectPr[ >]/g)||[]).length,1);assert.equal((merged.match(/w:type="page"/g)||[]).length,1);assert.match(merged,/w:pgBorders/);});
test('builtin certificates contain all records and one section per person',async()=>{const s=xml(await certificateBytes([{'姓名':'甲'},{'姓名':'乙'},{'姓名':'甲'}]));assert.equal((s.match(/<w:sectPr[ >]/g)||[]).length,3);assert.equal((s.match(/甲 同学/g)||[]).length,2)});
test('folded name cards use one A4 page per guest with matching upright and inverted text',async()=>{const s=xml(await nameCardBytes(['张三','李四','王五'],{size:96,subtitle:''}));for(const name of ['张三','李四','王五'])assert.equal((s.match(new RegExp(name,'g'))||[]).length,2);assert.equal((s.match(/<w:sectPr[ >]/g)||[]).length,3);assert.equal((s.match(/flip:x y;/g)||[]).length,3);assert.equal((s.match(/<v:textpath /g)||[]).length,6);assert.match(s,/w:w="11906"/);assert.match(s,/w:h="16838"/);});
test('ZIP retains distinct indexed names for duplicates',()=>{const z=new PizZip(zipFiles([{name:'001_甲.docx',bytes:new Uint8Array([1])},{name:'002_甲.docx',bytes:new Uint8Array([2])}]));assert.equal(Object.keys(z.files).length,2)});
test('custom folded WordArt template replaces both names and preserves upside-down shape',async()=>{const {prepareNameCardTemplate,wordArtStrings}=await import('../lib/namecard-templates.mjs');const template=await nameCardBytes(['李  岩']);const prepared=prepareNameCardTemplate(template,'李  岩');assert.equal(prepared.replacements,2);assert.deepEqual(inspectTemplate(prepared.bytes).fields,['姓名']);const filled=renderTemplate(prepared.bytes,{'姓名':'张 & 李'});assert.deepEqual(wordArtStrings(filled),['张 & 李']);assert.equal((xml(filled).match(/flip:x y;/g)||[]).length,1);assert.equal((xml(filled).match(/张 &amp; 李/g)||[]).length,2);});
test('plain custom template can replace an original name split across Word runs',async()=>{const {prepareNameCardTemplate}=await import('../lib/namecard-templates.mjs');const bytes=await certificateBytes([{'姓名':'张三'}]);const z=new PizZip(bytes);z.file('word/document.xml',z.file('word/document.xml').asText().replace('张三 同学','张</w:t></w:r><w:r><w:t>三 同学'));const prepared=prepareNameCardTemplate(z.generate({type:'uint8array'}),'张三');assert.equal(prepared.replacements,1);assert.match(xml(renderTemplate(prepared.bytes,{'姓名':'王五'})),/王五/);});
