'use client';
import {useMemo,useRef,useState} from 'react';
import {FileText,Upload,Plus,Trash2,Download,Eye,ChevronLeft,ChevronRight,Loader2} from 'lucide-react';
import {toast} from 'sonner';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {inspectTemplate,renderTemplate,mergeTemplateDocuments,zipFiles,download} from '@/lib/documents.mjs';
import {columnsToRecords} from '@/lib/template-data.mjs';
type Column={id:number;field:string;text:string};
export default function GeneralTemplate(){
 const [bytes,setBytes]=useState<Uint8Array|null>(null);const [filename,setFilename]=useState('');const [info,setInfo]=useState<any>(null);
 const [columns,setColumns]=useState<Column[]>([{id:0,field:'姓名',text:''},{id:1,field:'学号',text:''},{id:2,field:'联系方式',text:''}]);
 const nextId=useRef(3);const fileRef=useRef<HTMLInputElement>(null);const [pad,setPad]=useState(false);const [mode,setMode]=useState('zip');const [index,setIndex]=useState(0);const [busy,setBusy]=useState(false);const [reading,setReading]=useState(false);const [progress,setProgress]=useState('');
 const data=useMemo(()=>columnsToRecords(columns,info?.fields||[],pad),[columns,info,pad]);
 const selected=Math.min(index,Math.max(0,data.records.length-1));const current=data.records[selected];
 const errors=[...(!bytes?['请先上传 Word 模板']:info&&!info.fields.length?['模板中没有识别到占位符，请添加后重新上传']:[]),...data.errors,...(!data.count?['请粘贴需要填充的数据']:[])];
 function update(id:number,patch:Partial<Column>){setColumns(cs=>cs.map(c=>c.id===id?{...c,...patch}:c));setIndex(0)}
 async function upload(file:File){if(!/\.docx$/i.test(file.name)||file.size>10*1024*1024)return toast.error('请选择 10 MB 以内的 .docx 文件');setReading(true);try{const b=new Uint8Array(await file.arrayBuffer());const inspected=inspectTemplate(b);renderTemplate(b,Object.fromEntries(inspected.fields.map((f:string)=>[f,'示例'])));setBytes(b);setFilename(file.name);setInfo(inspected);setMode('zip');setIndex(0);setColumns(cs=>inspected.fields.map((field:string)=>({id:nextId.current++,field,text:cs.find(c=>c.field.trim()===field)?.text||''})));toast.success(`已识别 ${inspected.fields.length} 个字段，同名信息列的数据已保留`)}catch(e:any){toast.error(e.message||'无法读取模板')}finally{setReading(false)}}
 async function generate(){if(errors.length||!bytes||busy)return;setBusy(true);try{const files=[];for(let i=0;i<data.records.length;i++){setProgress(`正在生成 ${i+1} / ${data.count} 份`);if(i%5===0)await new Promise(r=>setTimeout(r,0));files.push({name:`${String(i+1).padStart(3,'0')}_填充文档.docx`,bytes:renderTemplate(bytes,data.records[i])});}const base=filename.replace(/\.docx$/i,'');download(mode==='zip'?zipFiles(files):mergeTemplateDocuments(files.map(f=>f.bytes)),base+'_批量填充.'+(mode==='zip'?'zip':'docx'),mode==='zip'?'application/zip':undefined);toast.success(`已生成 ${data.count} 份文档，下载已开始`)}catch(e:any){toast.error(e.message||'生成失败，请检查模板')}finally{setBusy(false);setProgress('')}}
 return <div className="editor-grid general-workspace"><div className="edit-panel"><fieldset disabled={busy||reading} className="general-controls">
 <section className="step"><div className="step-head"><span className="step-no">01</span><h2>上传自定义模板</h2></div><p className="helper">在 Word 中把要替换的文字改为 {'{姓名}'}、{'{学号}'}、{'{联系方式}'} 等占位符，可自定义字段名称。同一占位符出现多次会一起替换。</p>
 <div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&!reading&&e.dataTransfer.files[0])upload(e.dataTransfer.files[0])}}><input ref={fileRef} className="sr-only" type="file" accept=".docx" aria-label="上传通用 Word 模板" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value=''}}/><button className="drop-button" onClick={()=>fileRef.current?.click()}><span className="upload-icon word">{reading?<Loader2 className="spin"/>:<Upload/>}</span><strong>{reading?'正在读取模板…':filename||'点击上传 Word 模板，或拖拽到这里'}</strong><span>.docx · 最大 10 MB</span></button></div>
 {info&&<div className="general-tags">{info.fields.map((f:string)=><span key={f}>{'{'+f+'}'}</span>)}</div>}<p className="helper">替换文字，沿用原模板的字体、表格、图片和页面设置。内容变长可能导致自动换行或分页，请在打印前检查。</p></section>
 <section className="step"><div className="step-head"><span className="step-no">02</span><h2>粘贴字段数据</h2><div className="step-extra"><button className="text-button" onClick={()=>setColumns(cs=>[...cs,{id:nextId.current++,field:'',text:''}])}><Plus size={15}/>添加信息列</button></div></div><p className="helper">字段名称与模板中的占位符一致，不填花括号。每列粘贴一列数据，不含表头；各列的第 1 行对应第 1 份文档，以此类推。中间空行保留，末尾一个换行作为粘贴分隔符忽略。</p>
 <div className="general-columns">{columns.map((c,i)=><div className="general-column" key={c.id}><div className="general-column-head"><label className="field"><span>字段名称</span><input value={c.field} placeholder="例如：联系方式" aria-label={`第 ${i+1} 列字段名称`} onChange={e=>update(c.id,{field:e.target.value})}/></label><button className="general-delete" aria-label={`删除第 ${i+1} 列 ${c.field}`} onClick={()=>{setColumns(cs=>cs.filter(x=>x.id!==c.id));setIndex(0)}}><Trash2 size={17}/></button></div><textarea value={c.text} onChange={e=>update(c.id,{text:e.target.value})} placeholder={'每行一条数据\n可从 Excel 复制一列'} aria-label={`${c.field||'未命名字段'}的数据`} spellCheck={false}/><small>{data.counts[i]} 行{info&& !info.fields.includes(c.field.trim())?' · 模板未使用此字段':''}</small></div>)}</div>
 <label className="check-label general-padding"><Checkbox checked={pad} onCheckedChange={v=>setPad(v===true)}/>列长不一致时，缺失值留空</label><p className="helper">学号的前导零、电话号码和重复数据均保留。整行为空也会生成一份空白填充记录。</p></section>
 <section className="step"><div className="step-head"><span className="step-no">03</span><h2>批量导出</h2></div><label className="field"><span>导出方式</span><Select value={mode} onValueChange={setMode}><SelectTrigger className="choice"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="zip">独立 Word 文件 · ZIP 打包</SelectItem>{info?.canMerge&&<SelectItem value="merged">合并为一个 Word · 每条记录另起一页</SelectItem>}</SelectContent></Select></label>{info&&!info.canMerge&&<p className="helper">此模板含多节或页眉页脚变量，请使用独立 Word 文件，以保留每份文档的内容和布局。</p>}
 <div className="general-validation" role="status">{errors.length?errors.map((e:string,i:number)=><p key={i}>{e}</p>):<p>数据已就绪，将生成 {data.count} 份文档。</p>}</div><button className="button primary export-button" disabled={!!errors.length||busy||reading} onClick={generate}>{busy?<Loader2 size={18} className="spin"/>:<Download size={18}/>} {busy?progress:`生成并下载${data.count?' '+data.count+' 份文档':''}`}</button><p className="export-note">单次最多 500 条记录 · 默认保留独立文档布局</p></section></fieldset></div>
 <aside className="preview-panel"><div className="preview-top"><h2><Eye size={18}/>填充内容预览</h2><span className="preview-badge">{data.count} 条记录</span></div><div className="preview-canvas"><div className="uploaded-preview"><div className="document-label"><FileText size={17}/>{filename||'等待上传模板'}</div><div className="template-text">{info?info.text.replace(/\{([^{}]+)\}/g,(_:string,f:string)=>current&&Object.hasOwn(current,f.trim())?current[f.trim()]:'{'+f+'}'):'先上传带有占位符的 Word 模板，再为每个字段粘贴数据。'}</div><p className="helper">此处仅预览文本内容。原模板的样式与布局请查看下载后的 Word。</p></div></div><div className="preview-pagination"><span>当前记录</span><div><button aria-label="上一条记录" disabled={selected===0} onClick={()=>setIndex(selected-1)}><ChevronLeft size={16}/></button><span>{data.count?selected+1:0} / {data.count}</span><button aria-label="下一条记录" disabled={selected>=data.records.length-1} onClick={()=>setIndex(selected+1)}><ChevronRight size={16}/></button></div></div><div className="records-section"><div className="records-heading"><h3>数据对应检查</h3><span>前 {Math.min(10,data.count)} 条</span></div><Table className="records-table"><TableHeader><TableRow><TableHead>#</TableHead>{columns.map(c=><TableHead key={c.id}>{c.field||'未命名'}</TableHead>)}</TableRow></TableHeader><TableBody>{data.records.slice(0,10).map((r:Record<string,string>,i:number)=><TableRow key={i}><TableCell>{i+1}</TableCell>{columns.map(c=><TableCell key={c.id}>{r[c.field.trim()]||<span className="muted">（空）</span>}</TableCell>)}</TableRow>)}</TableBody></Table></div></aside></div>
}
